// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Site struct {
	ID          int32
	Name        string
	Url         string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Status      sql.NullString
}
