// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (name,url,description,created_at,updated_at)
VALUES(
    $1,$2,$3,$4,$5
)
RETURNING id, name, url, description, created_at, updated_at, status
`

type CreateSiteParams struct {
	Name        string
	Url         string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, createSite,
		arg.Name,
		arg.Url,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getSites = `-- name: GetSites :many
SELECT id, name, url, description, created_at, updated_at, status FROM sites
`

func (q *Queries) GetSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, getSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
